
# Validates Functions Framework with GCF buildpacks.
name: Buildpack Integration Test
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  go113-buildpack-test:
    uses: GoogleCloudPlatform/functions-framework-conformance/.github/workflows/buildpack-integration-test.yml@v1.4.1
    with:
      http-builder-source: 'testdata/conformance/function'
      http-builder-target: 'declarativeHTTP'
      cloudevent-builder-source: 'testdata/conformance/function'
      cloudevent-builder-target: 'declarativeCloudEvent'
      prerun: 'testdata/conformance/function/prerun.sh ${{ github.sha }}'
      builder-runtime: 'go113'
      # Latest uploaded tag from us.gcr.io/fn-img/us/buildpacks/go113/builder
      builder-tag: 'go113_20220320_1_13_15_RC00'
      start-delay: 5
  go116-buildpack-test:
    uses: GoogleCloudPlatform/functions-framework-conformance/.github/workflows/buildpack-integration-test.yml@v1.4.1
    with:
      http-builder-source: 'testdata/conformance/function'
      http-builder-target: 'declarativeHTTP'
      cloudevent-builder-source: 'testdata/conformance/function'
      cloudevent-builder-target: 'declarativeCloudEvent'
      prerun: 'testdata/conformance/function/prerun.sh ${{ github.sha }}'
      builder-runtime: 'go116'
      # Latest uploaded tag from us.gcr.io/fn-img/us/buildpacks/go116/builder
      builder-tag: 'go116_20220320_1_16_13_RC00'