on: [push, pull_request]

jobs:
  run-conformance:
    runs-on: ubuntu-latest
    name: Validate conformance test framework
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: '^1.13.1'

    - name: Format
      run: "find . -not \\( \\( -wholename './.git' \\) -prune \\) -name '*.go' | xargs gofmt -s -d"

    - name: Build and test
      run: "go test ./..."

    - name: Vet
      run: "go vet ./..."

      # To test this commit of the framework, specifically check it out in the test data.
    - name: Set up conformance test data
      run: "testdata/setup_conformance_test.sh"

    - name: Run HTTP conformance tests
      uses: GoogleCloudPlatform/functions-framework-conformance/action@v0.1.0
      with:
        functionType: 'http'
        validateMapping: false
        source: 'testdata'
        target: 'HTTP'
        runtime: 'go113'
        tag: 'go113_20200713_20_RC00'

    - name: Run event conformance tests
      uses: GoogleCloudPlatform/functions-framework-conformance/action@v0.1.0
      with:
        functionType: 'legacyevent'
        validateMapping: false
        source: 'testdata'
        target: 'Event'
        runtime: 'go113'
        tag: 'go113_20200713_20_RC00'

    # TODO: Enable once buildpack supports CloudEvents.
    # - name: Run cloudevent conformance tests
    #   uses: GoogleCloudPlatform/functions-framework-conformance/action@v0.1.0
    #   with:
    #     functionType: 'cloudevent'
    #     validateMapping: false
    #     source: 'testdata'
    #     target: 'CloudEvent'
    #     runtime: 'go113'
    #     tag: 'go113_20200713_20_RC00'
